Added Login and Register Screens
Dezenix/android-frontend-java pull request #7
Opened 2021-12-07 17:07 UTC by Kajal13081

Fixes #4 

@GovindSingh9447 Sir review this please.

2021-12-07 22:29 UTC, Ovenoboyo requested changes
Hi @Kajal13081, I've added some comments regarding some changes which will be needed before we further approve this PR. Kindly have a look at them.

Also some images are simply labeled as img, img1, ...
Please use meaningful naming conventions for them.

2021-12-07 22:29 UTC, Ovenoboyo commented on Register-And-Login-Screen/app/src/main/java/com/example/login_register_screen_ui/Login.java
> +        setContentView(R.layout.welcome_screen);
Unnecessary multiple setContentView

[Android docs](https://developer.android.com/reference/android/app/Activity#setContentView%28android.view.View%29) state that setContentView will overwrite any existing view

2021-12-07 22:29 UTC, Ovenoboyo commented on Register-And-Login-Screen/app/src/main/java/com/example/login_register_screen_ui/Login.java
> +        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);
Avoid setting fullscreen flag for any screen since it disrupts user experience

2021-12-07 22:29 UTC, Ovenoboyo commented on Register-And-Login-Screen/app/src/main/java/com/example/login_register_screen_ui/MainActivity.java
> +    TextView textView;
Class properties which are not going to be used outside the current class should be **private**

For example all UI related objects.

2021-12-07 22:29 UTC, Ovenoboyo commented on Register-And-Login-Screen/app/src/main/res/values/strings.xml
> +    <string name="todo">TODO</string>
Unecessary string. Use something sensible

2021-12-08 09:39 UTC, Kajal13081 commented
@Ovenoboyo I updated the changes. Please review it once.

2021-12-08 11:52 UTC, Ovenoboyo requested changes
Everything looks perfect. Only the strings need to be changes and ill approve this

2021-12-08 11:55 UTC, Kajal13081 commented
> Everything looks perfect. Only the strings need to be changes and ill approve this

What changes? Can you elaborate please

2021-12-08 12:00 UTC, Ovenoboyo commented
> > Everything looks perfect. Only the strings need to be changes and ill approve this
> 
> What changes? Can you elaborate please

In the previous review I had specified "unecessary string". That part was only meant for the "todo" string. I think due to some misunderstanding you have removed all strings from strings.xml and their usages too. So you'll just have to revert that part

2021-12-08 12:01 UTC, Kajal13081 commented
> > > Everything looks perfect. Only the strings need to be changes and ill approve this
> > 
> > 
> > What changes? Can you elaborate please
> 
> In the previous review I had specified "unecessary string". That part was only meant for the "todo" string. I think due to some misunderstanding you have removed all strings from strings.xml and their usages too. So you'll just have to revert that part

Okay

2021-12-08 12:20 UTC, Kajal13081 commented
@Ovenoboyo done. Please review it.

2021-12-08 12:29 UTC, Ovenoboyo requested changes
Sorry I previously missed this but your app/build folder needs to be in .gitignore. We will not be keeping any binary files on this repo

You can refer to this [file](/github/gitignore/tree/main/Android.gitignore) to know what all files are supposed to be ignored wile making a commit

Since you've already committed those files, You'll need to delete the app/build folder and commit all the deleted files again.

2021-12-08 12:44 UTC, Kajal13081 commented
![image](https://user-images.githubusercontent.com/80222700/145210420-8563bcab-4fd9-40c4-8308-2ee2c4b44451.png)
I have to commit only this folder na? @Ovenoboyo

2021-12-08 13:00 UTC, Kajal13081 commented
I have committed. Please do mention which files I need to delete more.

2021-12-08 13:56 UTC, merged

2021-12-08 13:58 UTC, Ovenoboyo commented
Moved to #9